[{
    "id": 345,
    "is_ready": true,
    "is_error": true,
    "params": {
        "limit": true,
        "count": 100,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 43,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.01.2020 3 месяца",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "false",
        "sortClick": "false",
        "sortClickI": "DESC",
        "sortRefuseTime": "false",
        "sortRdn": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2020-02-07_123853/docsReport_2020-02-07_123853.xlsx"
}, {
    "id": 317,
    "is_ready": false,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 500,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "false",
        "compPeriod": "Текущий",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-12-09_122616/docsReport_2019-12-09_122616.xlsx"
}, {
    "id": 290,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "undefined",
        "sortRefuseTime": "undefined",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_184509/docsReport_2019-10-31_184509.xlsx"
}, {
    "id": 289,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_184025/docsReport_2019-10-31_184025.xlsx"
}, {
    "id": 288,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Универсальный",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "false",
        "sortClickI": "ASC",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183929/docsReport_2019-10-31_183929.xlsx"
}, {
    "id": 287,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "false",
        "sortClickI": "ASC",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183853/docsReport_2019-10-31_183853.xlsx"
}, {
    "id": 286,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "true",
        "isDetail": "true",
        "sortClick": "false",
        "sortClickI": "ASC",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183837/docsReport_2019-10-31_183837.xlsx"
}, {
    "id": 285,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "true",
        "isDetail": "true",
        "sortClick": "false",
        "sortClickI": "DESC",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183819/docsReport_2019-10-31_183819.xlsx"
}, {
    "id": 284,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "true",
        "isDetail": "true",
        "sortClick": "ASC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183755/docsReport_2019-10-31_183755.xlsx"
}, {
    "id": 283,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "01.10.2018 12 месяцев",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "true",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183737/docsReport_2019-10-31_183737.xlsx"
}, {
    "id": 282,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "Текущий",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "true",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183715/docsReport_2019-10-31_183715.xlsx"
}, {
    "id": 281,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 25,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "true",
        "compPeriod": "Текущий",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "true",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-31_183649/docsReport_2019-10-31_183649.xlsx"
}, {
    "id": 219,
    "is_ready": true,
    "is_error": false,
    "params": {
        "limit": true,
        "count": 20,
        "base": "",
        "num": "",
        "label": "",
        "nameArt": "",
        "note": "",
        "from": 0,
        "to": 100,
        "period": "Текущий",
        "profile": "Все профили",
        "isComparison": "false",
        "compPeriod": "Текущий",
        "compProfile": "Все профили",
        "ms": "false",
        "fix": "false",
        "isDetail": "false",
        "sortClick": "DESC",
        "sortClickI": "false",
        "sortRefuseTime": "false",
        "sortRefuse": "false"
    },
    "path": "docs/reports/SUBD-NovoseltsevMS_2019-10-16_144406/docsReport_2019-10-16_144406.xlsx"
}]